FROM python:3.8-slim-buster

COPY ./requirements.txt /var/www/html/requirements.txt
RUN pip3 install -r requirements.txt
COPY ./ports.conf /etc/apache2/port.conf
COPY ./ports.conf /etc/apache2/sites-enabled/000-default.conf
COPY . /var/www/html/
